package dev.phonecode.app.auth

import dev.phonecode.provider.preset.CodexCompatibility
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import okhttp3.FormBody
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.IOException
import java.net.InetAddress
import java.net.ServerSocket
import java.net.Socket
import java.net.URLDecoder
import java.security.MessageDigest
import java.security.SecureRandom
import java.util.Base64
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Codex "Sign in with ChatGPT" OAuth 2.0 + PKCE data layer (see design/specs/codex-oauth.md).
 *
 * Mirrors the Codex CLI flow: PKCE auth-code grant against auth.openai.com with a loopback
 * redirect on port 1455 (the only confirmed-working redirect URI for this public client_id).
 * Tokens are persisted through the injected [store]/[read] pair (backed by SecureKeyStore on
 * device) under the keys `codex.access`, `codex.refresh`, `codex.expires` (epoch millis) and
 * `codex.account` (chatgpt_account_id, captured at initial login only - refreshed tokens omit it).
 */
class CodexAuth(
    private val http: OkHttpClient,
    private val store: (String, String) -> Unit,
    private val read: (String) -> String?,
    private val tokenEndpoint: String = TOKEN_ENDPOINT,
) {
    private val json = Json { ignoreUnknownKeys = true }
    private val refreshLock = Any()

    /** PKCE verifier generated by the last [buildAuthUrl] call; pass it to [exchangeCode]. */
    var pendingVerifier: String? = null
        private set

    /** State generated by the last [buildAuthUrl] call; compare against the callback's state. */
    var pendingState: String? = null
        private set

    @Volatile private var loopbacks: List<ServerSocket> = emptyList()

    // -- PKCE -------------------------------------------------------------------------------

    /** 32 random bytes, base64url without padding (RFC 7636 §4.1). */
    fun generateVerifier(): String = base64Url(ByteArray(32).also { SecureRandom().nextBytes(it) })

    /** S256 challenge: BASE64URL(SHA-256(ASCII(verifier))), no padding (RFC 7636 §4.2). */
    fun codeChallenge(verifier: String): String =
        base64Url(MessageDigest.getInstance("SHA-256").digest(verifier.toByteArray(Charsets.US_ASCII)))

    // -- Authorization ----------------------------------------------------------------------

    /** Builds the authorization URL, generating a fresh verifier/state pair as a side effect. */
    fun buildAuthUrl(): String {
        val verifier = generateVerifier()
        val state = base64Url(ByteArray(16).also { SecureRandom().nextBytes(it) })
        pendingVerifier = verifier
        pendingState = state
        return AUTH_ENDPOINT.toHttpUrl().newBuilder()
            .addQueryParameter("response_type", "code")
            .addQueryParameter("client_id", CLIENT_ID)
            .addQueryParameter("redirect_uri", REDIRECT_URI)
            .addQueryParameter("scope", SCOPE)
            .addQueryParameter("state", state)
            .addQueryParameter("code_challenge", codeChallenge(verifier))
            .addQueryParameter("code_challenge_method", "S256")
            .addQueryParameter("id_token_add_organizations", "true")
            .addQueryParameter("codex_cli_simplified_flow", "true")
            .addQueryParameter("originator", CodexCompatibility.ORIGINATOR)
            .build()
            .toString()
    }

    /**
     * Starts a one-shot loopback listener on 127.0.0.1:1455 for the OAuth redirect. Serves a tiny
     * "return to PhoneCode" page; only a callback whose `state` matches [expectedState] completes
     * the flow (mismatches are answered and ignored, so a stray request can't kill the listener).
     * Call [stopLoopback] to cancel (e.g. if the user abandons the browser flow).
     */
    fun startLoopback(
        expectedState: String,
        onError: (message: String) -> Unit = {},
        onCode: (code: String) -> Unit,
    ) {
        stopLoopback()
        val servers = listOf("127.0.0.1", "::1").mapNotNull { address ->
            runCatching { ServerSocket(LOOPBACK_PORT, 8, InetAddress.getByName(address)) }.getOrNull()
        }
        if (servers.isEmpty()) throw IOException("Could not open the Codex sign-in callback")
        loopbacks = servers
        val completed = AtomicBoolean(false)
        servers.forEach { server ->
            Thread({
                while (!server.isClosed && !completed.get()) {
                    val socket = try {
                        server.accept()
                    } catch (_: IOException) {
                        break
                    }
                    try {
                        socket.soTimeout = 10_000
                        val requestLine = socket.getInputStream().bufferedReader().readLine() ?: continue
                        val params = parseQueryParams(requestLine)
                        respondHtml(socket)
                        if (params["state"] != expectedState) continue
                        val code = params["code"]
                        val error = params["error_description"] ?: params["error"]
                        if (code == null && error == null) continue
                        if (!completed.compareAndSet(false, true)) continue
                        stopLoopback()
                        if (code != null) onCode(code) else onError(error!!)
                    } catch (_: IOException) {
                    } finally {
                        runCatching { socket.close() }
                    }
                }
            }, "codex-oauth-loopback").apply { isDaemon = true }.start()
        }
    }

    fun stopLoopback() {
        val servers = loopbacks
        loopbacks = emptyList()
        servers.forEach { runCatching { it.close() } }
    }

    /** Clear all persisted Codex tokens and stop any in-flight loopback (CodexAuth owns its own key names). */
    fun signOut() {
        listOf(KEY_ACCESS, KEY_REFRESH, KEY_EXPIRES, KEY_ACCOUNT).forEach { store(it, "") }
        stopLoopback()
    }

    // -- Token exchange & refresh -----------------------------------------------------------

    /** Exchanges the authorization code for tokens and persists them. Blocking; throws [IOException] on failure. */
    fun exchangeCode(code: String, verifier: String) {
        val token = postForToken(
            FormBody.Builder()
                .add("grant_type", "authorization_code")
                .add("code", code)
                .add("redirect_uri", REDIRECT_URI)
                .add("client_id", CLIENT_ID)
                .add("code_verifier", verifier)
                .build(),
        )
        persist(token)
        // Account id is only present on the initial login token, never after a refresh -
        // capture it now. The spec reports it in the id_token; fall back to the access token.
        val account = token.idToken?.let(::extractAccountId) ?: extractAccountId(token.accessToken)
        account?.let { store(KEY_ACCOUNT, it) }
    }

    /** Refreshes the access token if it expires within 60s and a refresh token exists. Blocking. */
    fun refreshIfNeeded() {
        synchronized(refreshLock) {
            val expires = read(KEY_EXPIRES)?.toLongOrNull() ?: return@synchronized
            if (System.currentTimeMillis() <= expires - REFRESH_MARGIN_MS) return@synchronized
            val refresh = read(KEY_REFRESH) ?: return@synchronized
            val token = postForToken(
                FormBody.Builder()
                    .add("grant_type", "refresh_token")
                    .add("client_id", CLIENT_ID)
                    .add("refresh_token", refresh)
                    .build(),
            )
            persist(token) // refresh tokens are single-use: rotation re-persists all three values
        }
    }

    /** A currently valid access token, refreshing first when needed, or null if signed out/expired. */
    fun accessToken(): String? {
        // A network failure while refreshing must honor the null/last-token contract, not throw IOException
        // out of a getter: fall through to the stored token and let the expiry check below decide.
        runCatching { refreshIfNeeded() }
        val access = read(KEY_ACCESS) ?: return null
        val expires = read(KEY_EXPIRES)?.toLongOrNull() ?: return null
        return if (System.currentTimeMillis() >= expires) null else access
    }

    /** The cached chatgpt_account_id from the initial login, for the ChatGPT-Account-Id header. */
    fun accountId(): String? = read(KEY_ACCOUNT)
        ?: read(KEY_ACCESS)?.let(::extractAccountId)?.also { store(KEY_ACCOUNT, it) }

    // -- Internals ---------------------------------------------------------------------------

    /** Extracts the chatgpt_account_id claim from a JWT payload (middle base64url segment). */
    fun extractAccountId(jwt: String): String? {
        val segment = jwt.split(".").getOrNull(1) ?: return null
        val claims = try {
            json.parseToJsonElement(String(Base64.getUrlDecoder().decode(segment), Charsets.UTF_8))
                as? JsonObject ?: return null
        } catch (_: IllegalArgumentException) {
            return null
        } catch (_: SerializationException) {
            return null
        }
        // Three-level fallback observed in the wild: bare claim, Auth0-namespaced object, dotted key.
        return claimString(claims["chatgpt_account_id"])
            ?: claimString((claims["https://api.openai.com/auth"] as? JsonObject)?.get("chatgpt_account_id"))
            ?: claimString(claims["https://api.openai.com/auth.chatgpt_account_id"])
            ?: claimString(((claims["organizations"] as? JsonArray)?.firstOrNull() as? JsonObject)?.get("id"))
    }

    private fun claimString(element: JsonElement?): String? =
        (element as? JsonPrimitive)?.contentOrNull?.takeIf { it.isNotEmpty() }

    private fun postForToken(body: FormBody): TokenResponse {
        val request = Request.Builder().url(tokenEndpoint).post(body).build()
        http.newCall(request).execute().use { response ->
            val text = response.body?.string().orEmpty()
            if (!response.isSuccessful) {
                throw IOException("Codex token request failed: HTTP ${response.code} ${text.take(300)}")
            }
            return json.decodeFromString(TokenResponse.serializer(), text)
        }
    }

    private fun persist(token: TokenResponse) {
        store(KEY_ACCESS, token.accessToken)
        token.refreshToken?.let { store(KEY_REFRESH, it) }
        store(KEY_EXPIRES, (System.currentTimeMillis() + token.expiresIn * 1000).toString())
    }

    /** Parses "GET /auth/callback?code=...&state=... HTTP/1.1" into decoded query params. */
    private fun parseQueryParams(requestLine: String): Map<String, String> {
        val target = requestLine.split(" ").getOrNull(1) ?: return emptyMap()
        val query = target.substringAfter('?', "")
        if (query.isEmpty()) return emptyMap()
        return query.split("&").mapNotNull { pair ->
            val eq = pair.indexOf('=')
            if (eq <= 0) return@mapNotNull null
            URLDecoder.decode(pair.take(eq), "UTF-8") to URLDecoder.decode(pair.substring(eq + 1), "UTF-8")
        }.toMap()
    }

    private fun respondHtml(socket: Socket) {
        val html = "<html><body><p>You can return to PhoneCode.</p></body></html>"
        val bytes = html.toByteArray(Charsets.UTF_8)
        socket.getOutputStream().apply {
            write(
                ("HTTP/1.1 200 OK\r\n" +
                    "Content-Type: text/html; charset=utf-8\r\n" +
                    "Content-Length: ${bytes.size}\r\n" +
                    "Connection: close\r\n\r\n").toByteArray(Charsets.US_ASCII),
            )
            write(bytes)
            flush()
        }
    }

    private fun base64Url(bytes: ByteArray): String =
        Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)

    @Serializable
    private data class TokenResponse(
        @SerialName("access_token") val accessToken: String,
        @SerialName("refresh_token") val refreshToken: String? = null,
        @SerialName("expires_in") val expiresIn: Long = DEFAULT_EXPIRES_IN_SECONDS,
        @SerialName("id_token") val idToken: String? = null,
    )

    companion object {
        /** Public client id of the Codex CLI; there is no client secret. */
        const val CLIENT_ID = "app_EMoamEEZ73f0CkXaXp7hrann"
        const val AUTH_ENDPOINT = "https://auth.openai.com/oauth/authorize"

        /** What the CLI posts to (auth.openai.com proxies the auth0 tenant). */
        const val TOKEN_ENDPOINT = "https://auth.openai.com/oauth/token"

        /** The only confirmed-working redirect URI for this client_id. */
        const val REDIRECT_URI = "http://localhost:1455/auth/callback"
        const val SCOPE = "openid profile email offline_access api.connectors.read api.connectors.invoke"
        const val LOOPBACK_PORT = 1455

        private const val KEY_ACCESS = "codex.access"
        private const val KEY_REFRESH = "codex.refresh"
        private const val KEY_EXPIRES = "codex.expires"
        private const val KEY_ACCOUNT = "codex.account"

        private const val REFRESH_MARGIN_MS = 60_000L
        private const val DEFAULT_EXPIRES_IN_SECONDS = 3_600L
    }
}
